/* eslint-disable @typescript-eslint/no-explicit-any -- RPC results are dynamic JSON; the tests assert on their shape */
import { createClient } from '@supabase/supabase-js'
import { beforeAll, describe, expect, it } from 'vitest'
import { baseCommission, maxDiscount, orderGross, type PricedLine } from '@/domain/orders/pricing'
import type { AppSupabaseClient } from '@/lib/supabase'
import type { Database } from '@/types/database.generated'
import { TEST_PASSWORD, TEST_USERS, getLocalConfig, serviceClient } from './helpers'

async function clientFor(email: string): Promise<AppSupabaseClient> {
  const { url, anonKey } = getLocalConfig()
  const client = createClient<Database>(url, anonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  })
  const { error } = await client.auth.signInWithPassword({ email, password: TEST_PASSWORD })
  if (error) throw error
  return client
}

// Loosely typed RPC call: tests pass nulls and extra keys on purpose.
const rpc = (client: AppSupabaseClient, fn: string, args: Record<string, unknown>) =>
  (
    client as unknown as {
      rpc: (
        f: string,
        a: unknown,
      ) => PromiseLike<{ data: Record<string, any>; error: Record<string, any> | null }>
    }
  ).rpc(fn, args)

interface Ids {
  customer: string
  products: Record<string, { id: string; price: number }>
}

let ids: Ids
let sale: AppSupabaseClient
let store: AppSupabaseClient
let admin: AppSupabaseClient
let warehouse: AppSupabaseClient

beforeAll(async () => {
  ;[sale, store, admin, warehouse] = await Promise.all([
    clientFor(TEST_USERS.sale),
    clientFor(TEST_USERS.store),
    clientFor(TEST_USERS.admin),
    clientFor(TEST_USERS.warehouse),
  ])
  const svc = serviceClient()
  const { data: customer } = await svc
    .from('customers')
    .select('id')
    .eq('phone_normalized', '0900000003')
    .single()
  const { data: products } = await svc.from('products').select('id, sku, list_price')
  ids = {
    customer: customer?.id as string,
    products: Object.fromEntries(
      (products ?? []).map((p) => [p.sku, { id: p.id, price: p.list_price }]),
    ),
  }
})

const item = (sku: string, quantity: number) => ({ product_id: ids.products[sku]?.id, quantity })

async function draft(
  client: AppSupabaseClient,
  items: unknown[],
  extra: Record<string, unknown> = {},
) {
  return rpc(client, 'save_draft_order', {
    p_order_id: null,
    p_customer_id: ids.customer,
    p_items: items,
    p_discount_amount: 0,
    ...extra,
  })
}

async function newDraft(client = sale, items: unknown[] = [item('TT-1200', 2)]) {
  const { data, error } = await draft(client, items)
  expect(error).toBeNull()
  return data as { id: string; order_code: string; status: string; net_amount: number }
}

async function action(client: AppSupabaseClient, id: string, act: string, reason?: string) {
  return rpc(client, 'transition_order', {
    p_order_id: id,
    p_action: act,
    p_reason: reason ?? null,
  })
}

describe('order code (ORD-002)', () => {
  it('is generated by the server with the configured prefix, ignoring client values', async () => {
    const a = await newDraft()
    const b = await newDraft()
    expect(a.order_code).toMatch(/^TET\d{6,}$/)
    expect(b.order_code).not.toBe(a.order_code)
    expect(Number(b.order_code.slice(3))).toBeGreaterThan(Number(a.order_code.slice(3)))
  })

  it('fails with a clear message when the prefix is not configured', async () => {
    const svc = serviceClient()
    const { data: setting } = await svc
      .from('app_settings')
      .select('*')
      .eq('key', 'order_prefix')
      .single()
    await svc.from('app_settings').delete().eq('key', 'order_prefix')
    try {
      const { error } = await draft(sale, [item('TT-1200', 1)])
      expect(error?.message).toMatch(/tiền tố mã đơn/)
    } finally {
      const restored = { ...(setting as Record<string, unknown>) }
      delete restored.id
      await svc.from('app_settings').insert(restored as never)
    }
  })
})

describe('pricing (ORD-003, ORD-004)', () => {
  it('snapshots list prices from products and computes gross/net on the server', async () => {
    const order = await newDraft(sale, [item('TT-1200', 3), item('HQ-A', 1)])
    const svc = serviceClient()
    const { data: row } = await svc
      .from('orders')
      .select('*, order_items(*)')
      .eq('id', order.id)
      .single()
    expect(row?.gross_amount).toBe(
      3 * (ids.products['TT-1200']?.price as number) + (ids.products['HQ-A']?.price as number),
    )
    expect(row?.net_amount).toBe(row?.gross_amount)
    expect(row?.discount_amount).toBe(0)
    expect(row?.remaining_amount).toBe(row?.net_amount)
    const lines = row?.order_items ?? []
    expect(lines).toHaveLength(2)
    for (const l of lines) expect(l.gross_line_amount).toBe(l.list_price * l.quantity)
  })

  it('ignores any price the client tries to send', async () => {
    const order = await newDraft(sale, [
      { ...item('TT-1200', 1), list_price: 1, gross_line_amount: 1 },
    ])
    const { data } = await serviceClient()
      .from('orders')
      .select('gross_amount')
      .eq('id', order.id)
      .single()
    expect(data?.gross_amount).toBe(ids.products['TT-1200']?.price)
  })

  it('merges duplicate products into one line', async () => {
    const order = await newDraft(sale, [item('TT-800', 1), item('TT-800', 2)])
    const { data } = await serviceClient()
      .from('order_items')
      .select('quantity')
      .eq('order_id', order.id)
    expect(data).toEqual([{ quantity: 3 }])
  })

  it('rejects empty orders, bad quantities, unknown and inactive products', async () => {
    for (const items of [
      [],
      [item('TT-1200', 0)],
      [item('TT-1200', -2)],
      [{ product_id: ids.products['TT-1200']?.id, quantity: 1.5 }],
      [{ product_id: ids.products['TT-1200']?.id, quantity: '2' }],
      [{ product_id: '00000000-0000-0000-0000-000000000000', quantity: 1 }],
      [item('DG-NGUNG', 1)],
    ]) {
      const { error } = await draft(sale, items)
      expect(error, JSON.stringify(items)).not.toBeNull()
    }
  })

  it('quote_order matches the TypeScript pricing functions', async () => {
    const cases = [
      [item('TT-1200', 1)],
      [item('TT-1200', 3), item('HQ-A', 2)],
      [item('HQ-C', 1), item('DG-TUI', 7), item('COM-500', 4)],
    ]
    for (const items of cases) {
      const { data, error } = await rpc(sale, 'quote_order', { p_items: items })
      expect(error).toBeNull()
      const lines: PricedLine[] = data.lines.map(
        (l: { list_price: number; quantity: number; commission_rate: number }) => ({
          listPrice: l.list_price,
          quantity: l.quantity,
          commissionRatePercent: Number(l.commission_rate),
        }),
      )
      expect(data.gross_amount).toBe(orderGross(lines))
      expect(data.max_discount_amount).toBe(maxDiscount(lines))
      expect(baseCommission(lines)).toBeGreaterThanOrEqual(data.max_discount_amount)
    }
  })
})

describe('commission ceiling and rate resolution (ORD-005, COM-001 priority)', () => {
  it('uses role+product (12%) before role (7%) before product default for the Sale role', async () => {
    const { data } = await rpc(sale, 'quote_order', {
      p_items: [item('HQ-A', 1), item('TT-1200', 1)],
    })
    const rates = Object.fromEntries(
      data.lines.map((l: { product_id: string; commission_rate: number }) => [
        l.product_id,
        Number(l.commission_rate),
      ]),
    )
    expect(rates[ids.products['HQ-A']?.id as string]).toBe(12)
    expect(rates[ids.products['TT-1200']?.id as string]).toBe(7)
  })

  it('prefers a user+product rule over the role rules (store user, TT-1200 = 5%)', async () => {
    const { data } = await rpc(store, 'quote_order', { p_items: [item('TT-1200', 1)] })
    expect(Number(data.lines[0].commission_rate)).toBe(5)
  })

  it('falls back to the product default when no rule matches (store user, TT-800 = 8%)', async () => {
    const { data } = await rpc(store, 'quote_order', { p_items: [item('TT-800', 1)] })
    expect(Number(data.lines[0].commission_rate)).toBe(8)
  })

  it('accepts a discount up to the ceiling and rejects one above it, naming the maximum', async () => {
    const { data: quote } = await rpc(sale, 'quote_order', { p_items: [item('HQ-A', 1)] })
    const max = quote.max_discount_amount as number
    expect(max).toBe(Math.floor((ids.products['HQ-A']?.price as number) * 0.12))

    const ok = await draft(sale, [item('HQ-A', 1)], { p_discount_amount: max })
    expect(ok.error).toBeNull()
    expect(ok.data.net_amount).toBe((ids.products['HQ-A']?.price as number) - max)

    const over = await draft(sale, [item('HQ-A', 1)], { p_discount_amount: max + 1 })
    expect(over.error?.code).toBe('P0001')
    expect(over.error?.message).toMatch(/vượt mức hoa hồng/)
    expect(over.error?.message).toContain(String(max))
  })

  it('rejects negative discounts and discounts above the order value', async () => {
    expect(
      (await draft(sale, [item('TT-1200', 1)], { p_discount_amount: -1 })).error,
    ).not.toBeNull()
    expect(
      (await draft(sale, [item('TT-1200', 1)], { p_discount_amount: 10 ** 9 })).error,
    ).not.toBeNull()
  })

  it('re-checks the ceiling on submit if rates dropped after the draft was saved', async () => {
    const svc = serviceClient()
    const { data: quote } = await rpc(sale, 'quote_order', { p_items: [item('HQ-B', 1)] })
    const created = await draft(sale, [item('HQ-B', 1)], {
      p_discount_amount: quote.max_discount_amount,
    })
    expect(created.error).toBeNull()

    // Admin-side change after the draft: a user-level rule of 0% for HQ-B starting today.
    const { data: saleProfile } = await svc
      .from('profiles')
      .select('id')
      .eq('full_name', 'Sale B2B Test')
      .single()
    const { data: rule } = await svc
      .from('commission_rules')
      .insert({
        user_id: saleProfile?.id as string,
        product_id: ids.products['HQ-B']?.id,
        rate_percent: 0,
        effective_from: '2026-01-01',
      })
      .select('id')
      .single()
    try {
      const submit = await action(sale, created.data.id, 'submit')
      expect(submit.error?.message).toMatch(/vượt mức hoa hồng/)
    } finally {
      await svc
        .from('commission_rules')
        .update({ is_active: false })
        .eq('id', rule?.id as string)
    }
    expect((await action(sale, created.data.id, 'submit')).error).toBeNull()
  })
})

describe('draft editing and attribution (ORD-006)', () => {
  it('fills owner, creator and attribution defaults from the profile', async () => {
    const order = await newDraft(store, [item('TT-800', 2)])
    const svc = serviceClient()
    const { data } = await svc
      .from('orders')
      .select(
        'owner_user_id, created_by, locations:creation_location_id(code), sales_channels:sales_channel_id(code), lead_sources:lead_source_id(code), profiles:owner_user_id(full_name)',
      )
      .eq('id', order.id)
      .single()
    expect(data?.owner_user_id).toBe(data?.created_by)
    expect(data?.profiles).toMatchObject({ full_name: 'Nhân viên cửa hàng Test' })
    expect(data?.locations).toMatchObject({ code: 'HN-CH1' })
    expect(data?.sales_channels).toMatchObject({ code: 'STORE' })
    expect(data?.lead_sources).toMatchObject({ code: 'WALK_IN' })
  })

  it('fully replaces the lines when a draft is edited', async () => {
    const order = await newDraft(sale, [item('TT-1200', 2), item('TT-800', 1)])
    const { data, error } = await draft(sale, [item('COM-800', 4)], {
      p_order_id: order.id,
      p_notes: '  ghi chú  ',
      p_requires_invoice: true,
    })
    expect(error).toBeNull()
    expect(data.id).toBe(order.id)
    expect(data.order_code).toBe(order.order_code)
    const { data: lines } = await serviceClient()
      .from('order_items')
      .select('quantity, products(sku)')
      .eq('order_id', order.id)
    expect(lines).toHaveLength(1)
    expect(lines?.[0]).toMatchObject({ quantity: 4, products: { sku: 'COM-800' } })
    const { data: row } = await serviceClient()
      .from('orders')
      .select('notes, requires_invoice')
      .eq('id', order.id)
      .single()
    expect(row).toEqual({ notes: 'ghi chú', requires_invoice: true })
  })

  it('rejects archived customers and inactive attribution values', async () => {
    const svc = serviceClient()
    const { data: archived } = await svc
      .from('customers')
      .select('id')
      .eq('phone_normalized', '0900000006')
      .single()
    expect(
      (await draft(sale, [item('TT-1200', 1)], { p_customer_id: archived?.id })).error?.message,
    ).toMatch(/khách hàng hợp lệ/)
  })

  it('lets only Admin create an order on behalf of another user', async () => {
    const { data: saleProfile } = await serviceClient()
      .from('profiles')
      .select('id')
      .eq('full_name', 'Sale B2B Test')
      .single()
    const byStore = await draft(store, [item('TT-1200', 1)], { p_owner_user_id: saleProfile?.id })
    expect(byStore.error).not.toBeNull()

    const byAdmin = await draft(admin, [item('TT-1200', 1)], {
      p_owner_user_id: saleProfile?.id,
      p_creation_location_id: null,
    })
    expect(byAdmin.error).toBeNull()
    expect(byAdmin.data.owner_user_id).toBe(saleProfile?.id)
    // the owner (not the creator) can now see and work on it
    const { data } = await sale.from('orders').select('id').eq('id', byAdmin.data.id)
    expect(data).toHaveLength(1)
  })

  it('denies roles that cannot create orders and inactive users', async () => {
    expect((await draft(warehouse, [item('TT-1200', 1)])).error).not.toBeNull()
    expect(
      (await rpc(warehouse, 'quote_order', { p_items: [item('TT-1200', 1)] })).error,
    ).not.toBeNull()
    const inactive = await clientFor(TEST_USERS.inactive)
    expect((await draft(inactive, [item('TT-1200', 1)])).error).not.toBeNull()
    // a non-admin cannot quote on behalf of someone else
    const { data: saleProfile } = await serviceClient()
      .from('profiles')
      .select('id')
      .eq('full_name', 'Sale B2B Test')
      .single()
    expect(
      (
        await rpc(store, 'quote_order', {
          p_owner_user_id: saleProfile?.id,
          p_items: [item('TT-1200', 1)],
        })
      ).error,
    ).not.toBeNull()
  })
})

describe('visibility and direct writes (RLS)', () => {
  it('shows each sales user only their own orders and Admin everything', async () => {
    const mine = await newDraft(sale)
    const theirs = await newDraft(store, [item('TT-800', 1)])
    const saleSees = ((await sale.from('orders').select('id')).data ?? []).map((o) => o.id)
    expect(saleSees).toContain(mine.id)
    expect(saleSees).not.toContain(theirs.id)
    const storeSees = ((await store.from('orders').select('id')).data ?? []).map((o) => o.id)
    expect(storeSees).toContain(theirs.id)
    expect(storeSees).not.toContain(mine.id)
    const adminSees = ((await admin.from('orders').select('id')).data ?? []).map((o) => o.id)
    expect(adminSees).toEqual(expect.arrayContaining([mine.id, theirs.id]))
    expect((await warehouse.from('orders').select('id')).data ?? []).toHaveLength(0)
  })

  it('hides lines and history of orders a user cannot see', async () => {
    const theirs = await newDraft(store, [item('TT-800', 1)])
    expect(
      (await sale.from('order_items').select('id').eq('order_id', theirs.id)).data,
    ).toHaveLength(0)
    expect(
      (await sale.from('order_status_history').select('id').eq('order_id', theirs.id)).data,
    ).toHaveLength(0)
    expect(
      (await store.from('order_items').select('id').eq('order_id', theirs.id)).data,
    ).toHaveLength(1)
  })

  it('blocks every direct client write to orders, lines and history', async () => {
    const order = await newDraft(sale)
    const insert = await sale.from('orders').insert({
      customer_id: ids.customer,
      owner_user_id: order.id,
      created_by: order.id,
      creation_location_id: order.id,
      sales_channel_id: order.id,
      lead_source_id: order.id,
      order_code: 'X',
    } as never)
    expect(insert.error).not.toBeNull()
    const update = await sale
      .from('orders')
      .update({ discount_amount: 999999999, status: 'COMPLETED' } as never)
      .eq('id', order.id)
      .select()
    expect(update.error !== null || (update.data ?? []).length === 0).toBe(true)
    const line = await sale
      .from('order_items')
      .update({ quantity: 999 })
      .eq('order_id', order.id)
      .select()
    expect(line.error !== null || (line.data ?? []).length === 0).toBe(true)
    const del = await sale.from('orders').delete().eq('id', order.id).select()
    expect(del.error !== null || (del.data ?? []).length === 0).toBe(true)
    const hist = await sale
      .from('order_status_history')
      .insert({ order_id: order.id, to_status: 'COMPLETED' })
    expect(hist.error).not.toBeNull()
    const { data } = await serviceClient()
      .from('orders')
      .select('status, discount_amount')
      .eq('id', order.id)
      .single()
    expect(data).toEqual({ status: 'DRAFT', discount_amount: 0 })
  })

  it("does not let another sales user edit or act on someone else's order", async () => {
    const order = await newDraft(sale)
    expect((await draft(store, [item('TT-800', 1)], { p_order_id: order.id })).error).not.toBeNull()
    expect((await action(store, order.id, 'submit')).error).not.toBeNull()
    expect((await action(store, order.id, 'cancel', 'thử')).error).not.toBeNull()
  })
})

describe('state transitions (ORD-007, ORD-008)', () => {
  it('walks submit -> confirm with the right actors and records history', async () => {
    const order = await newDraft(sale)
    expect((await action(sale, order.id, 'submit')).data.status).toBe('WAITING_CONFIRMATION')
    expect((await action(sale, order.id, 'confirm')).error?.code).toBe('42501') // not Admin
    expect((await action(admin, order.id, 'confirm')).data.status).toBe('WAITING_DEPOSIT')

    const { data: history } = await serviceClient()
      .from('order_status_history')
      .select('from_status, to_status')
      .eq('order_id', order.id)
      .order('created_at')
    expect(history).toEqual([
      { from_status: null, to_status: 'DRAFT' },
      { from_status: 'DRAFT', to_status: 'WAITING_CONFIRMATION' },
      { from_status: 'WAITING_CONFIRMATION', to_status: 'WAITING_DEPOSIT' },
    ])
  })

  it('refuses actions that do not fit the current state', async () => {
    const order = await newDraft(sale)
    expect((await action(sale, order.id, 'confirm')).error).not.toBeNull() // draft cannot be confirmed
    expect((await action(sale, order.id, 'return_to_draft')).error).not.toBeNull()
    await action(sale, order.id, 'submit')
    expect((await action(sale, order.id, 'submit')).error).not.toBeNull() // already submitted
    expect((await action(sale, order.id, 'teleport')).error?.message).toMatch(/không hợp lệ/)
  })

  it('returns an unpaid order to draft, where it can be edited again', async () => {
    const order = await newDraft(sale)
    await action(sale, order.id, 'submit')
    expect((await action(sale, order.id, 'return_to_draft')).data.status).toBe('DRAFT')
    expect((await draft(sale, [item('TT-500', 5)], { p_order_id: order.id })).error).toBeNull()
  })

  it('will not submit an order without lines', async () => {
    const svc = serviceClient()
    const order = await newDraft(sale)
    await svc.from('order_items').delete().eq('order_id', order.id) // draft lines may be removed
    expect((await action(sale, order.id, 'submit')).error?.message).toMatch(/ít nhất một sản phẩm/)
  })

  it('enforces the state machine in the database even for the service role', async () => {
    const svc = serviceClient()
    const order = await newDraft(sale)
    for (const target of ['CONFIRMED', 'COMPLETED', 'PREPARING', 'RETURNED']) {
      const { error } = await svc.from('orders').update({ status: target }).eq('id', order.id)
      expect(error?.message, target).toMatch(/Không thể chuyển/)
    }
    expect(
      (await svc.from('orders').select('status').eq('id', order.id).single()).data?.status,
    ).toBe('DRAFT')
  })
})

describe('confirmed orders are frozen (non-negotiable invariant)', () => {
  async function submitted() {
    const order = await newDraft(sale, [item('TT-1200', 2), item('TT-800', 1)])
    await action(sale, order.id, 'submit')
    return order
  }

  it('rejects editing a submitted order through the RPC with a cancel-and-recreate hint', async () => {
    const order = await submitted()
    const { error } = await draft(sale, [item('TT-1200', 99)], { p_order_id: order.id })
    expect(error?.message).toMatch(/hủy đơn cũ và tạo đơn mới/)
  })

  it('rejects any change to quantity, price, customer or amounts after the draft stage', async () => {
    const order = await submitted()
    const svc = serviceClient()
    const { data: lines } = await svc.from('order_items').select('id').eq('order_id', order.id)

    const qty = await svc
      .from('order_items')
      .update({ quantity: 50 })
      .eq('id', lines?.[0]?.id as string)
    expect(qty.error?.message).toMatch(/hủy đơn cũ và tạo đơn mới/)
    const price = await svc
      .from('order_items')
      .update({ list_price: 1, gross_line_amount: 1 })
      .eq('id', lines?.[0]?.id as string)
    expect(price.error).not.toBeNull()
    const del = await svc
      .from('order_items')
      .delete()
      .eq('id', lines?.[0]?.id as string)
    expect(del.error).not.toBeNull()
    const add = await svc.from('order_items').insert({
      order_id: order.id,
      product_id: ids.products['COM-500']?.id,
      quantity: 1,
      list_price: ids.products['COM-500']?.price,
      gross_line_amount: ids.products['COM-500']?.price,
    })
    expect(add.error).not.toBeNull()

    for (const patch of [
      { discount_amount: 1, net_amount: -1 },
      { gross_amount: 1 },
      { customer_id: ids.customer },
      { sales_channel_id: null },
    ]) {
      const { error } = await svc
        .from('orders')
        .update(patch as never)
        .eq('id', order.id)
      if ('customer_id' in patch) continue // same customer: unchanged value is not a change
      expect(error, JSON.stringify(patch)).not.toBeNull()
    }
    const { data: check } = await svc
      .from('order_items')
      .select('quantity')
      .eq('order_id', order.id)
      .order('quantity')
    expect(check?.map((c) => c.quantity)).toEqual([1, 2])
  })

  it('keeps the order code and creator unchangeable', async () => {
    const order = await newDraft(sale)
    const svc = serviceClient()
    expect(
      (await svc.from('orders').update({ order_code: 'HACK' }).eq('id', order.id)).error?.message,
    ).toMatch(/mã đơn/)
  })

  it('never hard-deletes orders or history, even for the service role', async () => {
    const order = await submitted()
    const svc = serviceClient()
    expect((await svc.from('orders').delete().eq('id', order.id)).error?.message).toMatch(
      /Không được xóa đơn hàng/,
    )
    expect(
      (await svc.from('order_status_history').delete().eq('order_id', order.id)).error?.message,
    ).toMatch(/bất biến/)
    expect(
      (await svc.from('order_status_history').update({ reason: 'x' }).eq('order_id', order.id))
        .error?.message,
    ).toMatch(/bất biến/)
  })
})

describe('cancel and void (ORD-009, ORD-010)', () => {
  it('lets the owner cancel an unpaid order with a reason, and records it', async () => {
    const order = await newDraft(sale)
    await action(sale, order.id, 'submit')
    expect((await action(sale, order.id, 'cancel')).error?.message).toMatch(/lý do hủy/)
    expect((await action(sale, order.id, 'cancel', '   ')).error?.message).toMatch(/lý do hủy/)

    const { data, error } = await action(sale, order.id, 'cancel', 'Khách đổi ý')
    expect(error).toBeNull()
    expect(data).toMatchObject({ status: 'CANCELLED', cancel_reason: 'Khách đổi ý' })
    expect(data.cancelled_at).not.toBeNull()

    const { data: history } = await serviceClient()
      .from('order_status_history')
      .select('to_status, reason, actor_user_id')
      .eq('order_id', order.id)
      .eq('to_status', 'CANCELLED')
      .single()
    expect(history?.reason).toBe('Khách đổi ý')
    expect(history?.actor_user_id).not.toBeNull()
    // terminal: no further transitions
    expect((await action(admin, order.id, 'void', 'x')).error).not.toBeNull()
  })

  it('lets only Admin cancel once an order is confirmed or reserved', async () => {
    const svc = serviceClient()
    const order = await newDraft(sale)
    await action(sale, order.id, 'submit')
    await action(admin, order.id, 'confirm')
    await svc
      .from('orders')
      .update({ status: 'CONFIRMED', confirmed_at: new Date().toISOString() })
      .eq('id', order.id) // stands in for the deposit step (E06)
    const owner = await action(sale, order.id, 'cancel', 'Muốn hủy')
    expect(owner.error?.code).toBe('42501')
    expect((await action(admin, order.id, 'cancel', 'Admin hủy')).data.status).toBe('CANCELLED')
  })

  it('refuses to cancel or void an order that already has a payment', async () => {
    const svc = serviceClient()
    const order = await newDraft(sale)
    await action(sale, order.id, 'submit')
    await svc.from('orders').update({ paid_amount: 1000 }).eq('id', order.id)
    expect((await action(sale, order.id, 'cancel', 'x')).error?.message).toMatch(/thanh toán/)
    expect((await action(admin, order.id, 'void', 'x')).error?.message).toMatch(/thanh toán/)
    expect((await action(sale, order.id, 'return_to_draft')).error?.message).toMatch(/thanh toán/)
    const { data } = await svc
      .from('orders')
      .select('remaining_amount, net_amount')
      .eq('id', order.id)
      .single()
    expect(data?.remaining_amount).toBe((data?.net_amount as number) - 1000)
  })

  it('voids (soft-deletes) only for Admin, with a reason, keeping the row and audit', async () => {
    const order = await newDraft(sale)
    expect((await action(sale, order.id, 'void', 'Nhập nhầm')).error?.code).toBe('42501')
    expect((await action(admin, order.id, 'void')).error?.message).toMatch(/lý do vô hiệu hóa/)
    const { data, error } = await action(admin, order.id, 'void', 'Nhập nhầm đơn')
    expect(error).toBeNull()
    expect(data).toMatchObject({ status: 'VOIDED', void_reason: 'Nhập nhầm đơn' })
    expect(data.voided_at).not.toBeNull()

    const svc = serviceClient()
    expect((await svc.from('orders').select('id').eq('id', order.id)).data).toHaveLength(1)
    const { data: audit } = await svc
      .from('audit_logs')
      .select('action')
      .eq('entity_type', 'orders')
      .eq('entity_id', order.id)
    expect((audit ?? []).length).toBeGreaterThanOrEqual(2)
    // the owner still sees the voided order (history is preserved)
    expect(
      (await sale.from('orders').select('status').eq('id', order.id).single()).data?.status,
    ).toBe('VOIDED')
  })

  it('cannot void orders past confirmation', async () => {
    const svc = serviceClient()
    const order = await newDraft(sale)
    await action(sale, order.id, 'submit')
    await action(admin, order.id, 'confirm')
    await svc.from('orders').update({ status: 'CONFIRMED' }).eq('id', order.id)
    await svc.from('orders').update({ status: 'RESERVED' }).eq('id', order.id)
    expect((await action(admin, order.id, 'void', 'x')).error?.message).toMatch(
      /không thể vô hiệu hóa/,
    )
    expect((await action(admin, order.id, 'cancel', 'đã giữ hàng')).data.status).toBe('CANCELLED')
  })
})
